### ISSUE TITLE
extend Readme

### ISSUE THREAD

**Issue by MarcSN311** [TobleMiner/HPE-FlexibleLOM-adapter#2]
Hi,
would be great if you could extend the readme a little bit. 

From my limited testing I think the host PCIe slot needs to provide 3.3V, can you confirm that?

Could you describe in which cases the jumpers need to be changed?

**Comment by TobleMiner** [comment]
Hi,

sure. I'm very open to ideas regarding a better README.

I'm not sure if the cards require 3.3V. On one of the SFP+ models I have the 3.3v rail is not connected to anything on the board. Might be that other cards need it though.

The jumpers were mostly there in case I messed up during reverse engineering.

I'll add a section to the README explaining what the different jumpers do.

**Comment by MarcSN311** [comment]
I had one of the Mellanox ConnectX-3 single port SFP+ cards lying around. I just measured and found the 3.3V Rail is connected to a bunch of caps on the board. 

A list of tested card with their requirements might be another useful addition to the Readme (or maybe the wiki?).

**Comment by TobleMiner** [comment]
Think 8cc9fc21a973bd5b9cdf8be47b14b1373eb9ac02 should make this a lot clearer

**Comment by TobleMiner** [comment]
@MarcSN311 
> I just measured and found the 3.3V Rail is connected to a bunch of caps on the board.

Yeah, nvm. Did not remember this correctly. The 3v3 aux are connected on my card, too. Guess it might be to keep connectivity via NC-SI even when +12V is missing?

**Comment by MarcSN311** [comment]
Thanks for the Readme update! I think this resolves the issue for me.
